### ISSUE TITLE
Make RME support different encodings from items.xml

### ISSUE THREAD

**Issue by EPuncker** [OTAcademy/RME#1]
For example if I have items.xml UTF-8 and item id 100 named `ground` it works **ok**

However, if I have items.xml UTF-16 (or any other encoding: ANSI, Windows-1252) and item id 100 named `chão` it will display blank item name and id:

![2022-04-29 15_41_43-Search for Item](https://user-images.githubusercontent.com/4684880/166006619-f6618c80-1342-4876-a50a-9077cf81a0fb.png)

this will be very useful for projects that have Multilanguage support or just not using English at all

**Comment by Zbizu** [comment]
That would require changing the way how the strings are stored in all tools - editor, server and client, but maybe I'm wrong. Have you tried adjusting the encoding in XML header itself?
