### ISSUE TITLE
Compilation bugs refered commit 83b3fbb

### ISSUE THREAD

**Issue by AnonyEd** [OTAcademy/RME#4]
There are some bugs in the commit 83b3fbb, preventing compilation.

palette_brushlist.cpp

Error (active)	E0020	identifier "wxID_ADD_TILESET" is undefined
Error (active)	E0020	identifier "wxID_ADD_TILESET" is undefined
Error (active)	E0020	identifier "wxID_ADD_ITEM_TO_TILESET" is undefined
Error (active)	E0020	identifier "wxID_ADD_ITEM_TO_TILESET" is undefined

**Comment by Zbizu** [comment]
fixed in 98d3362
